### ISSUE TITLE
AboutMe | Hate N' Hope

### ISSUE THREAD

**Issue by isr4z6er** [isr4z6er/blog-comments#5]
https://lozt.xyz/about/

**Comment by loztzol** [comment]
?

**Comment by isr4z6er** [comment]
2021年了。从来没有哪一年的元旦会像今年这么无望。《愿望清单》。

**Comment by isr4z6er** [comment]
需要理想，需要目标，需要计划。

**Comment by isr4z6er** [comment]
@isr4z6er 需要执行，需要回顾，需要总结

**Comment by isr4z6er** [comment]
@isr4z6er 人是复杂的，是“虚伪”的，是很难纯粹的。所以也不要轻易去评价别人，过分片面就变得毫无意义。

**Comment by isr4z6er** [comment]
@isr4z6er 规则最大的意义应当是保证公平。

**Comment by isr4z6er** [comment]
@isr4z6er 能够描述为体系类的东西，应当是可以做到自我闭环的。下单退单，扣费赔付等等。

**Comment by isr4z6er** [comment]
@isr4z6er 需求评审. 评: 需求背景及其合理性; 审: 可操作性与业务边界

**Comment by isr4z6er** [comment]
@isr4z6er 做事还是容易有头无尾, 不给个终结符, 怎么断连接.

**Comment by isr4z6er** [comment]
看着同事一个个走掉，你不明白他为什么走，就好像不明白自己为什么留。

**Comment by isr4z6er** [comment]
周五更新日，其他时间老实干活，稳定就好。

**Comment by isr4z6er** [comment]
> 看着同事一个个走掉，你不明白他为什么走，就好像不明白自己为什么留。

团队想要留住人，还是需要让人能有中归属感啊。团队里面如果一个人单干太久，又不能自己突破寻求帮助，时间久了基本就是无助愤怒加离职了。（何谓舒适的团队，至少，可以有效避免或解决内部矛盾，增强凝聚力才行

**Comment by isr4z6er** [comment]
累

**Comment by isr4z6er** [comment]
很累

**Comment by isr4z6er** [comment]
不要总是想要依赖别人，自己的追求，自己去争取。

**Comment by isr4z6er** [comment]
----

**Comment by isr4z6er** [comment]
人生观。什么样的人生是有意义的？ 如何才能让人生变得有意义？
----
To Leave Somthing About You Behind When You Say Goodbye To This World.

**Comment by isr4z6er** [comment]
每天都是一样的经历与感觉，这本身就是一件太过恐怖的事情。死亡轮回。求变，求轮回。

**Comment by isr4z6er** [comment]
@isr4z6er 目前遇到的两种域名不能用CDN的情况：1.邮件服务器域名，这个实际是可以，只不过Cloudflare免费版不支持，需要付费开通针对25 993 465等端口的转发； 2. Syncthing Discovery Server，在VPS已经使用Nginx反代了，接CDN之后不清楚是丢失了什么Header导致连不上或者连上之后查询无返回数据。（怀疑是X-Forwarded-For 和 X-Client-Port有问题 前者试着使用cf带过来的真实IP, in vain. 后者则无从传起）这个浪费太多时间了，就先换个不走CDN的域名得了。

**Comment by isr4z6er** [comment]
@isr4z6er 仔细想了下应该不是设置问题。而是Syncthing客户端与Discovery Client连接用的证书好像是自己生成的，走CDN之后CDN用自己的证书去连就有问题了？

**Comment by isr4z6er** [comment]
@isr4z6er 当大大大部分时间都需要自驱动的时候，要么就应该反思事情是不是有意义，要么就是要考虑是不是应该升级了。

**Comment by isr4z6er** [comment]
只有具体到实现细节的技术方案才叫有效方案。不能解决潜在问题的都是扯淡。😡
